# Generated by Django 5.0.6 on 2024-05-22 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Violations', '0003_rename_status_role_roles'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='role',
            options={'verbose_name': 'Роль', 'verbose_name_plural': 'Роли'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'Пользователь', 'verbose_name_plural': 'Пользователи'},
        ),
    ]
