# Generated by Django 5.0.6 on 2024-05-22 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Violations', '0005_status_application'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='roles',
            field=models.ManyToManyField(blank=True, to='Violations.role', verbose_name='Роли'),
        ),
    ]
