# Generated by Django 5.0.6 on 2024-05-22 19:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Violations', '0006_alter_user_roles'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='roles',
        ),
        migrations.DeleteModel(
            name='Role',
        ),
    ]
