# Generated by Django 5.0.6 on 2024-05-22 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Violations', '0007_remove_user_roles_delete_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='car_number',
            field=models.CharField(max_length=20, verbose_name='Номер автомобиля'),
        ),
        migrations.AlterField(
            model_name='application',
            name='description',
            field=models.TextField(max_length=300, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='application',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='applications/', verbose_name='Изображения'),
        ),
    ]
