# Generated by Django 5.0.6 on 2024-05-22 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Violations', '0008_alter_application_car_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='image',
            field=models.ImageField(default=1, upload_to='applications/', verbose_name='Изображения'),
            preserve_default=False,
        ),
    ]
